{
  "formatVersion": "1.1",
  "component": {
    "group": "org.hibernate.orm",
    "module": "hibernate-community-dialects",
    "version": "9.0.0.BOOT-MODEL",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.hibernate.orm",
          "module": "hibernate-platform",
          "version": {
            "requires": "9.0.0.BOOT-MODEL"
          },
          "excludes": [
            {
              "group": "xml-apis",
              "module": "xml-apis"
            }
          ],
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.hibernate.orm",
          "module": "hibernate-core",
          "version": {
            "requires": "9.0.0.BOOT-MODEL"
          },
          "excludes": [
            {
              "group": "xml-apis",
              "module": "xml-apis"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "hibernate-community-dialects-9.0.0.BOOT-MODEL.jar",
          "url": "hibernate-community-dialects-9.0.0.BOOT-MODEL.jar",
          "size": 835705,
          "sha512": "b24127bc1b30db579b1d73449ea774ea40a1080cae3492aa11e8423353c5685c95d6c92bf08d80c63bedad4e35db5245a6b10affed98b07a9d16da0e641b40bc",
          "sha256": "7273d2555d19924e388577ced18fd228b7f3314030f032b6c04532711c3e8a3a",
          "sha1": "71fa4f91d44c6c21b79c6bfe7a21fc33b89b5d68",
          "md5": "cd12905bb65a68c382576e72bbd90a2d"
        }
      ],
      "capabilities": [
        {
          "group": "org.hibernate",
          "name": "hibernate-community-dialects",
          "version": "9.0.0.BOOT-MODEL"
        },
        {
          "group": "org.hibernate.orm",
          "name": "hibernate-community-dialects",
          "version": "9.0.0.BOOT-MODEL"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jboss.logging",
          "module": "jboss-logging",
          "version": {
            "requires": "3.6.3.Final"
          },
          "excludes": [
            {
              "group": "xml-apis",
              "module": "xml-apis"
            }
          ]
        },
        {
          "group": "org.hibernate.orm",
          "module": "hibernate-platform",
          "version": {
            "requires": "9.0.0.BOOT-MODEL"
          },
          "excludes": [
            {
              "group": "xml-apis",
              "module": "xml-apis"
            }
          ],
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.hibernate.orm",
          "module": "hibernate-core",
          "version": {
            "requires": "9.0.0.BOOT-MODEL"
          },
          "excludes": [
            {
              "group": "xml-apis",
              "module": "xml-apis"
            }
          ]
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-core",
          "version": {
            "strictly": "[2.17.1, 3[",
            "requires": "[2.17.1, 3[",
            "prefers": "2.17.1"
          },
          "reason": "CVE-2021-44228, CVE-2021-45046, CVE-2021-45105, CVE-2021-44832: Log4j vulnerable to remote code execution and other critical security vulnerabilities"
        }
      ],
      "files": [
        {
          "name": "hibernate-community-dialects-9.0.0.BOOT-MODEL.jar",
          "url": "hibernate-community-dialects-9.0.0.BOOT-MODEL.jar",
          "size": 835705,
          "sha512": "b24127bc1b30db579b1d73449ea774ea40a1080cae3492aa11e8423353c5685c95d6c92bf08d80c63bedad4e35db5245a6b10affed98b07a9d16da0e641b40bc",
          "sha256": "7273d2555d19924e388577ced18fd228b7f3314030f032b6c04532711c3e8a3a",
          "sha1": "71fa4f91d44c6c21b79c6bfe7a21fc33b89b5d68",
          "md5": "cd12905bb65a68c382576e72bbd90a2d"
        }
      ],
      "capabilities": [
        {
          "group": "org.hibernate",
          "name": "hibernate-community-dialects",
          "version": "9.0.0.BOOT-MODEL"
        },
        {
          "group": "org.hibernate.orm",
          "name": "hibernate-community-dialects",
          "version": "9.0.0.BOOT-MODEL"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "hibernate-community-dialects-9.0.0.BOOT-MODEL-javadoc.jar",
          "url": "hibernate-community-dialects-9.0.0.BOOT-MODEL-javadoc.jar",
          "size": 5743815,
          "sha512": "9bba31bacd1569e488fbff708857bfeca8f859a0929350854648e6bb31a5bb6742c4e800e5aa1cb5b7e558ccf42c9b7b3c472c99af9c402b864b82eaf351152a",
          "sha256": "b865f21231744a945a0fec1be7c1b8845a08bbf3f361570a47fb43ca6b26c110",
          "sha1": "598b4b56fbb7f8e6edc47912104e81d9e5915da3",
          "md5": "29be16969c29c3a035f9ded1c6554f87"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "hibernate-community-dialects-9.0.0.BOOT-MODEL-sources.jar",
          "url": "hibernate-community-dialects-9.0.0.BOOT-MODEL-sources.jar",
          "size": 426768,
          "sha512": "e5ddf39e9d070f066e206b4d6f07b80b90228e8b56fa0987583cbc3d727a4d8272432807e880baa4be7d829d3726a6b437700e9129d533dd71135f9ea7dc4b0d",
          "sha256": "b57856a923b21b7e94f56559a3d4eb78ea46183793e0919403b5d6a61d567efe",
          "sha1": "0a0e281b0f46bdcef29e7abb57eab3515739ec3f",
          "md5": "e2fe6f0d5c68f393748a4e27e53a1f47"
        }
      ]
    }
  ]
}
