{
  "formatVersion": "1.1",
  "component": {
    "group": "org.hibernate.orm",
    "module": "hibernate-testing",
    "version": "9.0.0.BOOT-MODEL",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.hibernate.orm",
          "module": "hibernate-platform",
          "version": {
            "requires": "9.0.0.BOOT-MODEL"
          },
          "excludes": [
            {
              "group": "xml-apis",
              "module": "xml-apis"
            }
          ],
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.hibernate.orm",
          "module": "hibernate-core",
          "version": {
            "requires": "9.0.0.BOOT-MODEL"
          },
          "excludes": [
            {
              "group": "xml-apis",
              "module": "xml-apis"
            }
          ]
        },
        {
          "group": "org.hibernate.orm",
          "module": "hibernate-community-dialects",
          "version": {
            "requires": "9.0.0.BOOT-MODEL"
          },
          "excludes": [
            {
              "group": "xml-apis",
              "module": "xml-apis"
            }
          ]
        },
        {
          "group": "junit",
          "module": "junit",
          "version": {
            "requires": "4.13.2"
          },
          "excludes": [
            {
              "group": "xml-apis",
              "module": "xml-apis"
            }
          ]
        },
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter-api",
          "version": {
            "requires": "6.0.3"
          },
          "excludes": [
            {
              "group": "xml-apis",
              "module": "xml-apis"
            }
          ]
        },
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter-params",
          "version": {
            "requires": "6.0.3"
          },
          "excludes": [
            {
              "group": "xml-apis",
              "module": "xml-apis"
            }
          ]
        },
        {
          "group": "org.hamcrest",
          "module": "hamcrest",
          "version": {
            "requires": "3.0"
          },
          "excludes": [
            {
              "group": "xml-apis",
              "module": "xml-apis"
            }
          ]
        },
        {
          "group": "org.assertj",
          "module": "assertj-core",
          "version": {
            "requires": "3.26.3"
          },
          "excludes": [
            {
              "group": "xml-apis",
              "module": "xml-apis"
            }
          ]
        },
        {
          "group": "org.mockito",
          "module": "mockito-core",
          "version": {
            "requires": "5.23.0"
          },
          "excludes": [
            {
              "group": "xml-apis",
              "module": "xml-apis"
            }
          ]
        },
        {
          "group": "org.mockito",
          "module": "mockito-junit-jupiter",
          "version": {
            "requires": "5.23.0"
          },
          "excludes": [
            {
              "group": "xml-apis",
              "module": "xml-apis"
            }
          ]
        },
        {
          "group": "org.jboss.byteman",
          "module": "byteman-bmunit",
          "version": {
            "requires": "4.0.26"
          },
          "excludes": [
            {
              "group": "xml-apis",
              "module": "xml-apis"
            }
          ]
        },
        {
          "group": "org.jboss",
          "module": "jboss-transaction-spi",
          "version": {
            "requires": "8.0.0.Final"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jboss.narayana.jta",
          "module": "narayana-jta",
          "version": {
            "requires": "7.3.4.Final"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "javax.money",
          "module": "money-api",
          "version": {
            "requires": "1.1"
          },
          "excludes": [
            {
              "group": "xml-apis",
              "module": "xml-apis"
            }
          ]
        },
        {
          "group": "org.javamoney.moneta",
          "module": "moneta-core",
          "version": {
            "requires": "1.4.5"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-core",
          "version": {
            "requires": "2.26.0"
          },
          "excludes": [
            {
              "group": "xml-apis",
              "module": "xml-apis"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "hibernate-testing-9.0.0.BOOT-MODEL.jar",
          "url": "hibernate-testing-9.0.0.BOOT-MODEL.jar",
          "size": 895731,
          "sha512": "ef80fb8806f8917511cf3534d1cbb4d8009be10acf052c5226cd3d17339955189a67aaa88b10d0137a11c833eb285ab2e912c40b87779c341620ed8bd0700a60",
          "sha256": "ce6f368824fe52aee02e7df0777727bb2342b6ac611f8759c5d3bc7a8d4c2bb4",
          "sha1": "281aaabb1d7ffeedd98ce3c74685e986827d8d73",
          "md5": "6ea81623bcc8c2002ae3b1755c9e11a8"
        }
      ],
      "capabilities": [
        {
          "group": "org.hibernate",
          "name": "hibernate-testing",
          "version": "9.0.0.BOOT-MODEL"
        },
        {
          "group": "org.hibernate.orm",
          "name": "hibernate-testing",
          "version": "9.0.0.BOOT-MODEL"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jboss.logging",
          "module": "jboss-logging",
          "version": {
            "requires": "3.6.3.Final"
          },
          "excludes": [
            {
              "group": "xml-apis",
              "module": "xml-apis"
            }
          ]
        },
        {
          "group": "org.hibernate.models",
          "module": "hibernate-models",
          "version": {
            "requires": "1.1.1"
          },
          "excludes": [
            {
              "group": "xml-apis",
              "module": "xml-apis"
            }
          ]
        },
        {
          "group": "io.smallrye",
          "module": "jandex",
          "version": {
            "requires": "3.5.3"
          },
          "excludes": [
            {
              "group": "xml-apis",
              "module": "xml-apis"
            }
          ]
        },
        {
          "group": "org.wildfly.transaction",
          "module": "wildfly-transaction-client",
          "version": {
            "requires": "3.0.5.Final"
          },
          "excludes": [
            {
              "group": "xml-apis",
              "module": "xml-apis"
            },
            {
              "group": "org.wildfly.security",
              "module": "wildfly-elytron"
            }
          ]
        },
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter-engine",
          "version": {
            "requires": "6.0.3"
          },
          "excludes": [
            {
              "group": "xml-apis",
              "module": "xml-apis"
            }
          ]
        },
        {
          "group": "org.junit.platform",
          "module": "junit-platform-launcher",
          "version": {
            "requires": "6.0.3"
          },
          "excludes": [
            {
              "group": "xml-apis",
              "module": "xml-apis"
            }
          ]
        },
        {
          "group": "org.hibernate.orm",
          "module": "hibernate-platform",
          "version": {
            "requires": "9.0.0.BOOT-MODEL"
          },
          "excludes": [
            {
              "group": "xml-apis",
              "module": "xml-apis"
            }
          ],
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.hibernate.orm",
          "module": "hibernate-core",
          "version": {
            "requires": "9.0.0.BOOT-MODEL"
          },
          "excludes": [
            {
              "group": "xml-apis",
              "module": "xml-apis"
            }
          ]
        },
        {
          "group": "org.hibernate.orm",
          "module": "hibernate-community-dialects",
          "version": {
            "requires": "9.0.0.BOOT-MODEL"
          },
          "excludes": [
            {
              "group": "xml-apis",
              "module": "xml-apis"
            }
          ]
        },
        {
          "group": "junit",
          "module": "junit",
          "version": {
            "requires": "4.13.2"
          },
          "excludes": [
            {
              "group": "xml-apis",
              "module": "xml-apis"
            }
          ]
        },
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter-api",
          "version": {
            "requires": "6.0.3"
          },
          "excludes": [
            {
              "group": "xml-apis",
              "module": "xml-apis"
            }
          ]
        },
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter-params",
          "version": {
            "requires": "6.0.3"
          },
          "excludes": [
            {
              "group": "xml-apis",
              "module": "xml-apis"
            }
          ]
        },
        {
          "group": "org.hamcrest",
          "module": "hamcrest",
          "version": {
            "requires": "3.0"
          },
          "excludes": [
            {
              "group": "xml-apis",
              "module": "xml-apis"
            }
          ]
        },
        {
          "group": "org.assertj",
          "module": "assertj-core",
          "version": {
            "requires": "3.26.3"
          },
          "excludes": [
            {
              "group": "xml-apis",
              "module": "xml-apis"
            }
          ]
        },
        {
          "group": "org.mockito",
          "module": "mockito-core",
          "version": {
            "requires": "5.23.0"
          },
          "excludes": [
            {
              "group": "xml-apis",
              "module": "xml-apis"
            }
          ]
        },
        {
          "group": "org.mockito",
          "module": "mockito-junit-jupiter",
          "version": {
            "requires": "5.23.0"
          },
          "excludes": [
            {
              "group": "xml-apis",
              "module": "xml-apis"
            }
          ]
        },
        {
          "group": "org.jboss.byteman",
          "module": "byteman-bmunit",
          "version": {
            "requires": "4.0.26"
          },
          "excludes": [
            {
              "group": "xml-apis",
              "module": "xml-apis"
            }
          ]
        },
        {
          "group": "org.jboss",
          "module": "jboss-transaction-spi",
          "version": {
            "requires": "8.0.0.Final"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jboss.narayana.jta",
          "module": "narayana-jta",
          "version": {
            "requires": "7.3.4.Final"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "javax.money",
          "module": "money-api",
          "version": {
            "requires": "1.1"
          },
          "excludes": [
            {
              "group": "xml-apis",
              "module": "xml-apis"
            }
          ]
        },
        {
          "group": "org.javamoney.moneta",
          "module": "moneta-core",
          "version": {
            "requires": "1.4.5"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-core",
          "version": {
            "requires": "2.26.0"
          },
          "excludes": [
            {
              "group": "xml-apis",
              "module": "xml-apis"
            }
          ]
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-core",
          "version": {
            "strictly": "[2.17.1, 3[",
            "requires": "[2.17.1, 3[",
            "prefers": "2.17.1"
          },
          "reason": "CVE-2021-44228, CVE-2021-45046, CVE-2021-45105, CVE-2021-44832: Log4j vulnerable to remote code execution and other critical security vulnerabilities"
        }
      ],
      "files": [
        {
          "name": "hibernate-testing-9.0.0.BOOT-MODEL.jar",
          "url": "hibernate-testing-9.0.0.BOOT-MODEL.jar",
          "size": 895731,
          "sha512": "ef80fb8806f8917511cf3534d1cbb4d8009be10acf052c5226cd3d17339955189a67aaa88b10d0137a11c833eb285ab2e912c40b87779c341620ed8bd0700a60",
          "sha256": "ce6f368824fe52aee02e7df0777727bb2342b6ac611f8759c5d3bc7a8d4c2bb4",
          "sha1": "281aaabb1d7ffeedd98ce3c74685e986827d8d73",
          "md5": "6ea81623bcc8c2002ae3b1755c9e11a8"
        }
      ],
      "capabilities": [
        {
          "group": "org.hibernate",
          "name": "hibernate-testing",
          "version": "9.0.0.BOOT-MODEL"
        },
        {
          "group": "org.hibernate.orm",
          "name": "hibernate-testing",
          "version": "9.0.0.BOOT-MODEL"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "hibernate-testing-9.0.0.BOOT-MODEL-javadoc.jar",
          "url": "hibernate-testing-9.0.0.BOOT-MODEL-javadoc.jar",
          "size": 7664234,
          "sha512": "4c3e6413fe6b8d66522fce97936dcfb30854eb25cc4a97df7de3f156b517f1d575f74d1f57676656d5d839c6c6445188d90411eede0aa9eedef4bf843cf800d2",
          "sha256": "b55196eaa4d664744e95d8edd7d7025f260742334e0b54dc6dbf696ad8e520b0",
          "sha1": "c05d1f598c2575527e4cb58b985b784b83598444",
          "md5": "8ae2d757c3280cb1e404b052732c53ce"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "hibernate-testing-9.0.0.BOOT-MODEL-sources.jar",
          "url": "hibernate-testing-9.0.0.BOOT-MODEL-sources.jar",
          "size": 343415,
          "sha512": "ff0c52d5c0c1a59a49192e98511c9a4148fc597b25f972ada586f6916d6893b6da3f37f1a027503640b6e00b98b80dae52df8825a4b00e64216f36b65052079a",
          "sha256": "a86280891dd1eaa26f74f3e0c80af43003e6aaec670669da5d5337411a7b5ccc",
          "sha1": "f34ca12b198c6ea95271d184168373fb04b967bf",
          "md5": "b70aff2d80f0d29c18e86646dc04ea68"
        }
      ]
    }
  ]
}
