{
  "formatVersion": "1.1",
  "component": {
    "group": "org.hibernate.orm",
    "module": "hibernate-platform",
    "version": "9.0.0.BOOT-MODEL",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "platform",
        "org.gradle.usage": "java-api"
      },
      "dependencyConstraints": [
        {
          "group": "org.hibernate.orm",
          "module": "hibernate-core",
          "version": {
            "requires": "9.0.0.BOOT-MODEL"
          }
        },
        {
          "group": "org.hibernate",
          "module": "hibernate-core",
          "version": {
            "requires": "9.0.0.BOOT-MODEL"
          }
        },
        {
          "group": "org.hibernate.orm",
          "module": "hibernate-testing",
          "version": {
            "requires": "9.0.0.BOOT-MODEL"
          }
        },
        {
          "group": "org.hibernate",
          "module": "hibernate-testing",
          "version": {
            "requires": "9.0.0.BOOT-MODEL"
          }
        },
        {
          "group": "org.hibernate.orm",
          "module": "hibernate-envers",
          "version": {
            "requires": "9.0.0.BOOT-MODEL"
          }
        },
        {
          "group": "org.hibernate",
          "module": "hibernate-envers",
          "version": {
            "requires": "9.0.0.BOOT-MODEL"
          }
        },
        {
          "group": "org.hibernate.orm",
          "module": "hibernate-spatial",
          "version": {
            "requires": "9.0.0.BOOT-MODEL"
          }
        },
        {
          "group": "org.hibernate",
          "module": "hibernate-spatial",
          "version": {
            "requires": "9.0.0.BOOT-MODEL"
          }
        },
        {
          "group": "org.hibernate.orm",
          "module": "hibernate-vector",
          "version": {
            "requires": "9.0.0.BOOT-MODEL"
          }
        },
        {
          "group": "org.hibernate",
          "module": "hibernate-vector",
          "version": {
            "requires": "9.0.0.BOOT-MODEL"
          }
        },
        {
          "group": "org.hibernate.orm",
          "module": "hibernate-community-dialects",
          "version": {
            "requires": "9.0.0.BOOT-MODEL"
          }
        },
        {
          "group": "org.hibernate",
          "module": "hibernate-community-dialects",
          "version": {
            "requires": "9.0.0.BOOT-MODEL"
          }
        },
        {
          "group": "org.hibernate.orm",
          "module": "hibernate-scan-jandex",
          "version": {
            "requires": "9.0.0.BOOT-MODEL"
          }
        },
        {
          "group": "org.hibernate.orm",
          "module": "hibernate-agroal",
          "version": {
            "requires": "9.0.0.BOOT-MODEL"
          }
        },
        {
          "group": "org.hibernate",
          "module": "hibernate-agroal",
          "version": {
            "requires": "9.0.0.BOOT-MODEL"
          }
        },
        {
          "group": "org.hibernate.orm",
          "module": "hibernate-c3p0",
          "version": {
            "requires": "9.0.0.BOOT-MODEL"
          }
        },
        {
          "group": "org.hibernate",
          "module": "hibernate-c3p0",
          "version": {
            "requires": "9.0.0.BOOT-MODEL"
          }
        },
        {
          "group": "org.hibernate.orm",
          "module": "hibernate-hikaricp",
          "version": {
            "requires": "9.0.0.BOOT-MODEL"
          }
        },
        {
          "group": "org.hibernate",
          "module": "hibernate-hikaricp",
          "version": {
            "requires": "9.0.0.BOOT-MODEL"
          }
        },
        {
          "group": "org.hibernate.orm",
          "module": "hibernate-jcache",
          "version": {
            "requires": "9.0.0.BOOT-MODEL"
          }
        },
        {
          "group": "org.hibernate",
          "module": "hibernate-jcache",
          "version": {
            "requires": "9.0.0.BOOT-MODEL"
          }
        },
        {
          "group": "org.hibernate.orm",
          "module": "hibernate-micrometer",
          "version": {
            "requires": "9.0.0.BOOT-MODEL"
          }
        },
        {
          "group": "org.hibernate",
          "module": "hibernate-micrometer",
          "version": {
            "requires": "9.0.0.BOOT-MODEL"
          }
        },
        {
          "group": "org.hibernate.orm",
          "module": "hibernate-graalvm",
          "version": {
            "requires": "9.0.0.BOOT-MODEL"
          }
        },
        {
          "group": "org.hibernate",
          "module": "hibernate-graalvm",
          "version": {
            "requires": "9.0.0.BOOT-MODEL"
          }
        },
        {
          "group": "org.hibernate.orm",
          "module": "hibernate-processor",
          "version": {
            "requires": "9.0.0.BOOT-MODEL"
          }
        },
        {
          "group": "org.hibernate",
          "module": "hibernate-processor",
          "version": {
            "requires": "9.0.0.BOOT-MODEL"
          }
        },
        {
          "group": "org.hibernate.orm",
          "module": "hibernate-gradle-plugin",
          "version": {
            "requires": "9.0.0.BOOT-MODEL"
          }
        },
        {
          "group": "org.hibernate.orm",
          "module": "hibernate-maven-plugin",
          "version": {
            "requires": "9.0.0.BOOT-MODEL"
          }
        },
        {
          "group": "org.hibernate.orm",
          "module": "hibernate-ant",
          "version": {
            "requires": "9.0.0.BOOT-MODEL"
          }
        },
        {
          "group": "org.hibernate",
          "module": "hibernate-ant",
          "version": {
            "requires": "9.0.0.BOOT-MODEL"
          }
        },
        {
          "group": "org.hibernate.orm",
          "module": "hibernate-assistant",
          "version": {
            "requires": "9.0.0.BOOT-MODEL"
          }
        },
        {
          "group": "org.hibernate",
          "module": "hibernate-assistant",
          "version": {
            "requires": "9.0.0.BOOT-MODEL"
          }
        },
        {
          "group": "org.hibernate.orm",
          "module": "hibernate-reveng",
          "version": {
            "requires": "9.0.0.BOOT-MODEL"
          }
        },
        {
          "group": "org.hibernate",
          "module": "hibernate-reveng",
          "version": {
            "requires": "9.0.0.BOOT-MODEL"
          }
        },
        {
          "group": "org.hibernate.orm",
          "module": "hibernate-jfr",
          "version": {
            "requires": "9.0.0.BOOT-MODEL"
          }
        },
        {
          "group": "org.hibernate",
          "module": "hibernate-jfr",
          "version": {
            "requires": "9.0.0.BOOT-MODEL"
          }
        },
        {
          "group": "org.hibernate.models",
          "module": "hibernate-models",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "jakarta.persistence",
          "module": "jakarta.persistence-api",
          "version": {
            "requires": "4.0.0-M3"
          }
        },
        {
          "group": "jakarta.transaction",
          "module": "jakarta.transaction-api",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "jakarta.data",
          "module": "jakarta.data-api",
          "version": {
            "requires": "1.1.0-M3"
          }
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "platform",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "org.antlr",
          "module": "antlr4-runtime",
          "version": {
            "requires": "4.13.2"
          }
        },
        {
          "group": "org.jboss.logging",
          "module": "jboss-logging",
          "version": {
            "requires": "3.6.3.Final"
          }
        },
        {
          "group": "net.bytebuddy",
          "module": "byte-buddy",
          "version": {
            "requires": "1.18.8"
          }
        },
        {
          "group": "net.bytebuddy",
          "module": "byte-buddy-agent",
          "version": {
            "requires": "1.18.8"
          }
        },
        {
          "group": "io.smallrye",
          "module": "jandex",
          "version": {
            "requires": "3.5.3"
          }
        },
        {
          "group": "org.glassfish.jaxb",
          "module": "jaxb-runtime",
          "version": {
            "requires": "4.0.8"
          }
        },
        {
          "group": "jakarta.xml.bind",
          "module": "jakarta.xml.bind-api",
          "version": {
            "requires": "4.0.5"
          }
        },
        {
          "group": "jakarta.inject",
          "module": "jakarta.inject-api",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "io.agroal",
          "module": "agroal-api",
          "version": {
            "requires": "3.1.2"
          }
        },
        {
          "group": "io.agroal",
          "module": "agroal-pool",
          "version": {
            "requires": "3.1.2"
          }
        },
        {
          "group": "com.mchange",
          "module": "c3p0",
          "version": {
            "requires": "0.13.0"
          }
        },
        {
          "group": "com.zaxxer",
          "module": "HikariCP",
          "version": {
            "requires": "7.0.2"
          }
        },
        {
          "group": "javax.cache",
          "module": "cache-api",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "io.micrometer",
          "module": "micrometer-core",
          "version": {
            "requires": "1.16.5"
          }
        },
        {
          "group": "org.hibernate.orm",
          "module": "hibernate-core",
          "version": {
            "requires": "9.0.0.BOOT-MODEL"
          }
        },
        {
          "group": "org.hibernate",
          "module": "hibernate-core",
          "version": {
            "requires": "9.0.0.BOOT-MODEL"
          }
        },
        {
          "group": "org.hibernate.orm",
          "module": "hibernate-testing",
          "version": {
            "requires": "9.0.0.BOOT-MODEL"
          }
        },
        {
          "group": "org.hibernate",
          "module": "hibernate-testing",
          "version": {
            "requires": "9.0.0.BOOT-MODEL"
          }
        },
        {
          "group": "org.hibernate.orm",
          "module": "hibernate-envers",
          "version": {
            "requires": "9.0.0.BOOT-MODEL"
          }
        },
        {
          "group": "org.hibernate",
          "module": "hibernate-envers",
          "version": {
            "requires": "9.0.0.BOOT-MODEL"
          }
        },
        {
          "group": "org.hibernate.orm",
          "module": "hibernate-spatial",
          "version": {
            "requires": "9.0.0.BOOT-MODEL"
          }
        },
        {
          "group": "org.hibernate",
          "module": "hibernate-spatial",
          "version": {
            "requires": "9.0.0.BOOT-MODEL"
          }
        },
        {
          "group": "org.hibernate.orm",
          "module": "hibernate-vector",
          "version": {
            "requires": "9.0.0.BOOT-MODEL"
          }
        },
        {
          "group": "org.hibernate",
          "module": "hibernate-vector",
          "version": {
            "requires": "9.0.0.BOOT-MODEL"
          }
        },
        {
          "group": "org.hibernate.orm",
          "module": "hibernate-community-dialects",
          "version": {
            "requires": "9.0.0.BOOT-MODEL"
          }
        },
        {
          "group": "org.hibernate",
          "module": "hibernate-community-dialects",
          "version": {
            "requires": "9.0.0.BOOT-MODEL"
          }
        },
        {
          "group": "org.hibernate.orm",
          "module": "hibernate-scan-jandex",
          "version": {
            "requires": "9.0.0.BOOT-MODEL"
          }
        },
        {
          "group": "org.hibernate.orm",
          "module": "hibernate-agroal",
          "version": {
            "requires": "9.0.0.BOOT-MODEL"
          }
        },
        {
          "group": "org.hibernate",
          "module": "hibernate-agroal",
          "version": {
            "requires": "9.0.0.BOOT-MODEL"
          }
        },
        {
          "group": "org.hibernate.orm",
          "module": "hibernate-c3p0",
          "version": {
            "requires": "9.0.0.BOOT-MODEL"
          }
        },
        {
          "group": "org.hibernate",
          "module": "hibernate-c3p0",
          "version": {
            "requires": "9.0.0.BOOT-MODEL"
          }
        },
        {
          "group": "org.hibernate.orm",
          "module": "hibernate-hikaricp",
          "version": {
            "requires": "9.0.0.BOOT-MODEL"
          }
        },
        {
          "group": "org.hibernate",
          "module": "hibernate-hikaricp",
          "version": {
            "requires": "9.0.0.BOOT-MODEL"
          }
        },
        {
          "group": "org.hibernate.orm",
          "module": "hibernate-jcache",
          "version": {
            "requires": "9.0.0.BOOT-MODEL"
          }
        },
        {
          "group": "org.hibernate",
          "module": "hibernate-jcache",
          "version": {
            "requires": "9.0.0.BOOT-MODEL"
          }
        },
        {
          "group": "org.hibernate.orm",
          "module": "hibernate-micrometer",
          "version": {
            "requires": "9.0.0.BOOT-MODEL"
          }
        },
        {
          "group": "org.hibernate",
          "module": "hibernate-micrometer",
          "version": {
            "requires": "9.0.0.BOOT-MODEL"
          }
        },
        {
          "group": "org.hibernate.orm",
          "module": "hibernate-graalvm",
          "version": {
            "requires": "9.0.0.BOOT-MODEL"
          }
        },
        {
          "group": "org.hibernate",
          "module": "hibernate-graalvm",
          "version": {
            "requires": "9.0.0.BOOT-MODEL"
          }
        },
        {
          "group": "org.hibernate.orm",
          "module": "hibernate-processor",
          "version": {
            "requires": "9.0.0.BOOT-MODEL"
          }
        },
        {
          "group": "org.hibernate",
          "module": "hibernate-processor",
          "version": {
            "requires": "9.0.0.BOOT-MODEL"
          }
        },
        {
          "group": "org.hibernate.orm",
          "module": "hibernate-gradle-plugin",
          "version": {
            "requires": "9.0.0.BOOT-MODEL"
          }
        },
        {
          "group": "org.hibernate.orm",
          "module": "hibernate-maven-plugin",
          "version": {
            "requires": "9.0.0.BOOT-MODEL"
          }
        },
        {
          "group": "org.hibernate.orm",
          "module": "hibernate-ant",
          "version": {
            "requires": "9.0.0.BOOT-MODEL"
          }
        },
        {
          "group": "org.hibernate",
          "module": "hibernate-ant",
          "version": {
            "requires": "9.0.0.BOOT-MODEL"
          }
        },
        {
          "group": "org.hibernate.orm",
          "module": "hibernate-assistant",
          "version": {
            "requires": "9.0.0.BOOT-MODEL"
          }
        },
        {
          "group": "org.hibernate",
          "module": "hibernate-assistant",
          "version": {
            "requires": "9.0.0.BOOT-MODEL"
          }
        },
        {
          "group": "org.hibernate.orm",
          "module": "hibernate-reveng",
          "version": {
            "requires": "9.0.0.BOOT-MODEL"
          }
        },
        {
          "group": "org.hibernate",
          "module": "hibernate-reveng",
          "version": {
            "requires": "9.0.0.BOOT-MODEL"
          }
        },
        {
          "group": "org.hibernate.orm",
          "module": "hibernate-jfr",
          "version": {
            "requires": "9.0.0.BOOT-MODEL"
          }
        },
        {
          "group": "org.hibernate",
          "module": "hibernate-jfr",
          "version": {
            "requires": "9.0.0.BOOT-MODEL"
          }
        },
        {
          "group": "org.hibernate.models",
          "module": "hibernate-models",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "jakarta.persistence",
          "module": "jakarta.persistence-api",
          "version": {
            "requires": "4.0.0-M3"
          }
        },
        {
          "group": "jakarta.transaction",
          "module": "jakarta.transaction-api",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "jakarta.data",
          "module": "jakarta.data-api",
          "version": {
            "requires": "1.1.0-M3"
          }
        }
      ]
    }
  ]
}
